name: $(SourceBranchName) $(Rev:r)
pr: none

pool:
  vmImage: 'windows-2019'

steps:
- task: Gradle@2
  displayName: 'Build Library'
  inputs:
    workingDirectory: ''
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: false
    tasks: 'build'

- task: PublishPipelineArtifact@0
  displayName: 'Save JAR File'
  inputs:
    targetPath: 'build/libs'
